version: '3'

services:

    database:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: symfony_guestbook
            POSTGRES_PASSWORD: symfony_guestbook
            POSTGRES_DB: symfony_guestbook
        ports:
            - 5432:5432

    redis:
        image: redis:5-alpine
        ports:
            - 6379:6379

    rabbitmq:
        image: rabbitmq:3.7-management
        ports:
            - 5672:15672

    adminer:
        image: adminer
        environment:
            ADMINER_DESIGN: pepa-linha
            ADMINER_DEFAULT_SERVER: symfony_guestbook
        links:
            - database
        ports:
            - 8888:8080
